name: tugas_aplikasi_youtube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: "YouTube"
      fonts:
        - asset: "assets/fonts/YouTubeSansLight.otf"
          weight: 100
        - asset: "assets/fonts/YouTubeSansRegular.otf"
          weight: 400
        - asset: "assets/fonts/YouTubeSansMedium.otf"
          weight: 500
        - asset: "assets/fonts/YouTubeSansBold.otf"
          weight: 700